language: bash

language: php

language: python

before_script:
- sudo apt-get install pandoc
- sudo apt-get install python3-pip
- sudo apt-get update
- sudo apt-get install xvfb libfontconfig wkhtmltopdf
- sudo apt-get update
- sudo apt-get install -y texlive-base
- sudo apt-get update

script: 
- wkhtmltopdf --version
- pandoc --version
- pdflatex --version
- ls
- cd /legacy/odt1718/
